
import { GoogleGenAI } from "@google/genai";

export async function editMobileImage(base64Image: string, prompt: string, mimeType: string = 'image/jpeg'): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image.split(',')[1],
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:${mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image generated by the AI model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
}
